import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import AuthProvider from "@/provider/auth-provider";
import RtkProvider from "@/provider/rtk-provider";
import { auth } from "@/auth";
import SessionProvider from "@/provider/session-provider";
import CountDown from "@/components/count-down";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body>
        <div
          className={`${geistSans.variable} ${geistMono.variable} antialiased w-full max-w-7xl grid mx-auto px-4 `}
        >
          <AuthProvider>
            <SessionProvider session={session}>
              <RtkProvider>
                <CountDown />
                <Navbar />
                {children}
                <Toaster />
                <Footer />
              </RtkProvider>
            </SessionProvider>
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
